import { useQuery } from '@tanstack/react-query';
import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Clock, DoorOpen, Filter, Search, UserRound, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { coordinationApi } from '@/core/api/coordination.api';
import type { Assignment, ScheduleDay } from '@/core/api/types';
import { useDebounce } from '@/shared/hooks/use-debounce';
import { Badge, Button, Card, EmptyState, Skeleton, cn } from '@/shared/components/ui';

const dayLabels: Record<ScheduleDay, string> = { monday: 'Lun', tuesday: 'Mar', wednesday: 'Mié', thursday: 'Jue', friday: 'Vie', saturday: 'Sáb', sunday: 'Dom' };

export function AllocationPage() {
  const [search, setSearch] = useState(''); const [coordinationId, setCoordinationId] = useState(''); const [page, setPage] = useState(1); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [cycle, setCycle] = useState(''); const [level, setLevel] = useState(''); const debouncedSearch = useDebounce(search);
  const overview = useQuery({ queryKey: ['coordination', 'overview'], queryFn: coordinationApi.overview });
  const teachers = useQuery({ queryKey: ['coordination', 'teachers', debouncedSearch, coordinationId, page], queryFn: () => coordinationApi.teachers({ search: debouncedSearch || undefined, coordinationId: coordinationId || undefined, page, pageSize: 20 }) });
  useEffect(() => { setPage(1); }, [debouncedSearch, coordinationId]);
  useEffect(() => { if (!selectedId && teachers.data?.data[0]) setSelectedId(teachers.data.data[0].id); }, [selectedId, teachers.data]);
  const detail = useQuery({ queryKey: ['coordination', 'teacher', selectedId], queryFn: () => coordinationApi.assignments(selectedId!), enabled: Boolean(selectedId) });
  const options = useMemo(() => { const items = detail.data?.data.assignments ?? []; return { cycles: [...new Set(items.map((item) => item.schoolCycleName || item.schoolCycleExternalId))], levels: [...new Set(items.map((item) => item.educationLevel).filter(Boolean))] as string[] }; }, [detail.data]);
  const assignments = useMemo(() => (detail.data?.data.assignments ?? []).filter((item) => (!cycle || (item.schoolCycleName || item.schoolCycleExternalId) === cycle) && (!level || item.educationLevel === level)), [detail.data, cycle, level]);
  return <div className="grid min-h-[calc(100vh-9rem)] gap-5 xl:grid-cols-[360px_1fr]">
    <Card className="flex min-h-[640px] flex-col overflow-hidden"><div className="border-b border-slate-200 p-4"><label className="relative block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="field pl-10" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Nombre o matrícula" aria-label="Buscar profesor"/></label><select className="field mt-3" value={coordinationId} onChange={(e) => setCoordinationId(e.target.value)} aria-label="Filtrar por coordinación"><option value="">Todas las coordinaciones</option>{overview.data?.data.coordinations.map((item) => <option key={item.id} value={item.id}>{item.shortName || item.name}</option>)}</select></div>
      <div className="flex-1 overflow-y-auto p-2" aria-live="polite">{teachers.isLoading ? <div className="space-y-2 p-2">{Array.from({ length: 7 }, (_, index) => <Skeleton key={index} className="h-20"/>)}</div> : teachers.data?.data.length === 0 ? <div className="p-4"><EmptyState icon={<Users/>} title="Sin resultados" description="Prueba con otro nombre, matrícula o coordinación."/></div> : teachers.data?.data.map((teacher) => <button key={teacher.id} onClick={() => { setSelectedId(teacher.id); setCycle(''); setLevel(''); }} className={cn('mb-1 w-full rounded-lg border px-3 py-3 text-left transition', selectedId === teacher.id ? 'border-red-200 bg-red-50' : 'border-transparent hover:bg-slate-50')}><div className="flex items-start gap-3"><div className={cn('mt-0.5 grid h-9 w-9 place-items-center rounded-full text-sm font-bold', selectedId === teacher.id ? 'bg-[#C8102E] text-white' : 'bg-slate-100 text-slate-600')}>{teacher.name.slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{teacher.name}</p><p className="mt-0.5 truncate text-xs text-slate-500">{teacher.institutionalCode || teacher.email || 'Sin identificador'}</p><p className="mt-1 text-xs text-slate-400">{teacher.assignmentCount} grupos · {teacher.subjectCount} materias</p></div></div></button>)}</div>
      <div className="flex items-center justify-between border-t border-slate-200 p-3 text-xs text-slate-500"><span>{teachers.data?.meta.total ?? 0} profesores</span><div className="flex items-center gap-1"><Button variant="ghost" className="h-8 w-8 p-0" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} aria-label="Página anterior"><ChevronLeft size={17}/></Button><span className="px-2">{page}/{Math.max(1, teachers.data?.meta.totalPages ?? 1)}</span><Button variant="ghost" className="h-8 w-8 p-0" disabled={page >= (teachers.data?.meta.totalPages ?? 1)} onClick={() => setPage((value) => value + 1)} aria-label="Página siguiente"><ChevronRight size={17}/></Button></div></div>
    </Card>
    <section className="min-w-0">{!selectedId ? <EmptyState icon={<UserRound size={38}/>} title="Selecciona un profesor" description="Elige un profesor para inspeccionar su carga académica recolectada."/> : detail.isLoading ? <div className="space-y-4"><Skeleton className="h-28"/><Skeleton className="h-52"/><Skeleton className="h-52"/></div> : detail.isError || !detail.data ? <EmptyState icon={<BookOpen size={36}/>} title="No pudimos cargar la asignación" description="Intenta seleccionar nuevamente al profesor."/> : <div className="space-y-5"><Card className="p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#C8102E]">Profesor seleccionado</p><h2 className="mt-1 text-2xl font-bold">{detail.data.data.teacher.name}</h2><p className="mt-1 text-sm text-slate-500">{detail.data.data.teacher.email || detail.data.data.teacher.institutionalCode}</p></div><div className="flex flex-wrap gap-2"><Badge>{detail.data.data.teacher.assignmentCount} grupos</Badge><Badge>{detail.data.data.teacher.subjectCount} materias</Badge>{detail.data.data.teacher.lastHarvestedAt && <Badge tone="success">Actualizado {new Date(detail.data.data.teacher.lastHarvestedAt).toLocaleDateString('es-MX')}</Badge>}</div></div></Card>
          <div className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><Filter size={17} className="text-slate-400"/><select className="field w-auto min-w-48" value={cycle} onChange={(e) => setCycle(e.target.value)}><option value="">Todos los ciclos</option>{options.cycles.map((item) => <option key={item}>{item}</option>)}</select><select className="field w-auto min-w-48" value={level} onChange={(e) => setLevel(e.target.value)}><option value="">Todos los niveles</option>{options.levels.map((item) => <option key={item}>{item}</option>)}</select><span className="ml-auto text-xs text-slate-500">{assignments.length} resultados</span></div>
          {assignments.length === 0 ? <EmptyState icon={<CalendarDays size={36}/>} title="Sin asignaciones para estos filtros" description="Cambia el ciclo o nivel educativo para ampliar la búsqueda."/> : <div className="grid gap-4 2xl:grid-cols-2">{assignments.map((item) => <AssignmentCard key={item.id} assignment={item}/>)}</div>}
        </div>}</section>
  </div>;
}

function AssignmentCard({ assignment }: { assignment: Assignment }) {
  const scheduledDays = Object.entries(assignment.schedule).filter(([, slots]) => slots.length > 0) as Array<[ScheduleDay, Assignment['schedule'][ScheduleDay]]>;
  return <Card className="overflow-hidden border-slate-300"><div className="border-l-4 border-[#C8102E] p-5"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex flex-wrap gap-2"><Badge tone="info">Grupo {assignment.groupCode || assignment.externalGroupId}</Badge><Badge>{assignment.schoolCycleName || assignment.schoolCycleExternalId}</Badge></div><h3 className="text-lg font-bold leading-snug">{assignment.subject.name}</h3><p className="mt-1 text-xs text-slate-500">{assignment.subject.code || `ID ${assignment.subject.externalId}`}</p></div><BookOpen className="shrink-0 text-slate-300"/></div><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 text-sm sm:grid-cols-2"><div className="flex items-center gap-2 text-slate-600"><DoorOpen size={17} className="text-[#C8102E]"/><span><b className="text-slate-800">Salón:</b> {assignment.classroom || 'Sin dato'}</span></div><div className="flex items-center gap-2 text-slate-600"><GraduationCapIcon/><span>{assignment.educationLevel || 'Nivel no identificado'}</span></div></div><div className="mt-4 space-y-2">{scheduledDays.length ? scheduledDays.map(([day, slots]) => <div key={day} className="flex items-center gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="w-8 font-bold text-slate-700">{dayLabels[day]}</span><Clock size={15} className="text-slate-400"/><span className="text-slate-600">{slots.map((slot) => slot.startTime && slot.endTime ? `${slot.startTime}–${slot.endTime}` : slot.raw).join(', ')}</span></div>) : <p className="rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-800">Horario todavía no recolectado.</p>}</div></div></Card>;
}
function GraduationCapIcon() { return <span className="grid h-[17px] w-[17px] place-items-center text-[#C8102E]">◆</span>; }
